// SPDX-License-Identifier: BSD-3-Clause
// https://github.com/AcademySoftwareFoundation/OpenShadingLanguage


// This file contains "declarations" for all the strings that might get used in
// JITed shader code or in renderer code. But the declaration itself is
// dependent on the RS_STRDECL macro, which should be declared by the outer file
// prior to including this file. Thus, this list may be repurposed and included
// multiple times, with different RS_STRDECL definitions.


#ifndef RS_STRDECL
#    error Do not include this file unless RS_STRDECL is defined
#endif


RS_STRDECL("osl:version", osl_version)
RS_STRDECL("camera:resolution", camera_resolution)
RS_STRDECL("camera:projection", camera_projection)
RS_STRDECL("camera:pixelaspect", camera_pixelaspect)
RS_STRDECL("camera:screen_window", camera_screen_window)
RS_STRDECL("camera:fov", camera_fov)
RS_STRDECL("camera:clip", camera_clip)
RS_STRDECL("camera:clip_near", camera_clip_near)
RS_STRDECL("camera:clip_far", camera_clip_far)
RS_STRDECL("camera:shutter", camera_shutter)
RS_STRDECL("camera:shutter_open", camera_shutter_open)
RS_STRDECL("camera:shutter_close", camera_shutter_close)
RS_STRDECL("perspective", perspective)
RS_STRDECL("raster", raster)
RS_STRDECL("myspace", myspace)
RS_STRDECL("options", options)
RS_STRDECL("blahblah", blahblah)
RS_STRDECL("s", s)
RS_STRDECL("t", t)
RS_STRDECL("mouse", mouse)

RS_STRDECL("", _emptystring_)
RS_STRDECL("camera", camera)
RS_STRDECL("common", common)
RS_STRDECL("object", object)
RS_STRDECL("shader", shader)
RS_STRDECL("screen", screen)
RS_STRDECL("NDC", NDC)
RS_STRDECL("rgb", rgb)
RS_STRDECL("RGB", RGB)
RS_STRDECL("hsv", hsv)
RS_STRDECL("hsl", hsl)
RS_STRDECL("YIQ", YIQ)
RS_STRDECL("XYZ", XYZ)
RS_STRDECL("xyz", xyz)
RS_STRDECL("xyY", xyY)
RS_STRDECL("null", null)
RS_STRDECL("default", default_)
RS_STRDECL("label", label)
RS_STRDECL("sidedness", sidedness)
RS_STRDECL("front", front)
RS_STRDECL("back", back)
RS_STRDECL("both", both)
RS_STRDECL("P", P)
RS_STRDECL("I", I)
RS_STRDECL("N", N)
RS_STRDECL("Ng", Ng)
RS_STRDECL("dPdu", dPdu)
RS_STRDECL("dPdv", dPdv)
RS_STRDECL("u", u)
RS_STRDECL("v", v)
RS_STRDECL("Ps", Ps)
RS_STRDECL("time", time)
RS_STRDECL("dtime", dtime)
RS_STRDECL("dPdtime", dPdtime)
RS_STRDECL("Ci", Ci)
RS_STRDECL("width", width)
RS_STRDECL("swidth", swidth)
RS_STRDECL("twidth", twidth)
RS_STRDECL("rwidth", rwidth)
RS_STRDECL("blur", blur)
RS_STRDECL("sblur", sblur)
RS_STRDECL("tblur", tblur)
RS_STRDECL("rblur", rblur)
RS_STRDECL("wrap", wrap)
RS_STRDECL("swrap", swrap)
RS_STRDECL("twrap", twrap)
RS_STRDECL("rwrap", rwrap)
RS_STRDECL("black", black)
RS_STRDECL("clamp", clamp)
RS_STRDECL("periodic", periodic)
RS_STRDECL("mirror", mirror)
RS_STRDECL("firstchannel", firstchannel)
RS_STRDECL("fill", fill)
RS_STRDECL("alpha", alpha)
RS_STRDECL("error", error)
RS_STRDECL("errormessage", errormessage)
RS_STRDECL("trace", trace)
RS_STRDECL("mindist", mindist)
RS_STRDECL("maxdist", maxdist)
RS_STRDECL("shade", shade)
RS_STRDECL("traceset", traceset)
RS_STRDECL("interp", interp)
RS_STRDECL("closest", closest)
RS_STRDECL("linear", linear)
RS_STRDECL("cubic", cubic)
RS_STRDECL("catmull-rom", catmullrom)
RS_STRDECL("bezier", bezier)
RS_STRDECL("bspline", bspline)
RS_STRDECL("hermite", hermite)
RS_STRDECL("constant", constant)
RS_STRDECL("smartcubic", smartcubic)
RS_STRDECL("perlin", perlin)
RS_STRDECL("uperlin", uperlin)
RS_STRDECL("noise", noise)
RS_STRDECL("snoise", snoise)
RS_STRDECL("cell", cell)
RS_STRDECL("cellnoise", cellnoise)
RS_STRDECL("pcellnoise", pcellnoise)
RS_STRDECL("hash", hash)
RS_STRDECL("hashnoise", hashnoise)
RS_STRDECL("phashnoise", phashnoise)
RS_STRDECL("pnoise", pnoise)
RS_STRDECL("psnoise", psnoise)
RS_STRDECL("genericnoise", genericnoise)
RS_STRDECL("genericpnoise", genericpnoise)
RS_STRDECL("gabor", gabor)
RS_STRDECL("gabornoise", gabornoise)
RS_STRDECL("gaborpnoise", gaborpnoise)
RS_STRDECL("simplex", simplex)
RS_STRDECL("usimplex", usimplex)
RS_STRDECL("simplexnoise", simplexnoise)
RS_STRDECL("usimplexnoise", usimplexnoise)
RS_STRDECL("anisotropic", anisotropic)
RS_STRDECL("direction", direction)
RS_STRDECL("do_filter", do_filter)
RS_STRDECL("bandwidth", bandwidth)
RS_STRDECL("impulses", impulses)
RS_STRDECL("dowhile", op_dowhile)
RS_STRDECL("for", op_for)
RS_STRDECL("while", op_while)
RS_STRDECL("exit", op_exit)
RS_STRDECL("subimage", subimage)
RS_STRDECL("subimagename", subimagename)
RS_STRDECL("missingcolor", missingcolor)
RS_STRDECL("missingalpha", missingalpha)
RS_STRDECL("end", end)
RS_STRDECL("useparam", useparam)
RS_STRDECL("!!!uninitialized!!!", uninitialized_string)
RS_STRDECL("unull", unull)
RS_STRDECL("raytype", raytype)
RS_STRDECL("color", color)
RS_STRDECL("point", point)
RS_STRDECL("vector", vector)
RS_STRDECL("normal", normal)
RS_STRDECL("matrix", matrix)
RS_STRDECL("Rec709", Rec709)
RS_STRDECL("sRGB", sRGB)
RS_STRDECL("NTSC", NTSC)
RS_STRDECL("EBU", EBU)
RS_STRDECL("PAL", PAL)
RS_STRDECL("SECAM", SECAM)
RS_STRDECL("SMPTE", SMPTE)
RS_STRDECL("HDTV", HDTV)
RS_STRDECL("CIE", CIE)
RS_STRDECL("AdobeRGB", AdobeRGB)
RS_STRDECL("ACES2065-1", ACES2065_1)
RS_STRDECL("ACEScg", ACEScg)
RS_STRDECL("colorsystem", colorsystem)
RS_STRDECL("arraylength", arraylength)
RS_STRDECL("unknown", unknown)
RS_STRDECL("ERROR: Unknown color space transformation \"%s\" -> \"%s\"\n",
        ErrorColorTransform)
RS_STRDECL("world", world)
